name: form_framework
description: Framework para geração de formulários.
version: 1.0.0

environment:
  sdk: '>=2.19.1 <3.0.0'


dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0

dependencies:
  shelf: ^1.2.0
  shelf_router: ^1.1.3
  sqlite3: ^1.0.0
  reflectable: ^3.0.0